### PR TITLE
cmake package

### PR DESCRIPTION
**Pull request by aerorahul**
Keeping up with the packaging work of @kgerheiser, this PR adds that capability to CRTM.
Since there is no `develop` branch, this PR is merging into `release/public-v1`  
There are no changes necessary downstream.

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
Let's create ``develop`` branch to make this repository consistent with other NCEPLIBS-* and make it easy to write install scripts that loop over all libraries.

**Comment by aerorahul** [comment]
> Let's create `develop` branch to make this repository consistent with other NCEPLIBS-* and make it easy to write install scripts that loop over all libraries.

I have no issues with creating a `develop` branch so long as it is understood that this project is not under development.  I would sooner rather than later move over to the authoritative CRTM repository and decommission this.

**Comment by DusanJovic-NOAA** [comment]
I see this repository is not a GitHub fork of another repository. Where is CRTM's authoritative repository and who maintains it?

**Comment by aerorahul** [comment]
> I see this repository is not a GitHub fork of another repository. Where is CRTM's authoritative repository and who maintains it?

This is the CRTM's authoritative repository [here](https://github.com/JCSDA/CRTM_dev)
JCSDA maintains a releases from there.

**Comment by DusanJovic-NOAA** [comment]
I get "Page not found" error when I click [here](https://github.com/JCSDA/CRTM_dev). Is this public repository?

**Comment by DusanJovic-NOAA** [comment]
I compiled successfully this branch on WCOSS Dell and linked ufs-weather-model using crtm::crtm imported target.

**Comment by aerorahul** [comment]
> I get "Page not found" error when I click [here](https://github.com/JCSDA/CRTM_dev). Is this public repository?

It is under the JCSDA organization.  Nevertheless, the repository looks nothing like this one.  It is hopeless to expect a cleaned up repository that we can simply fork and use for our purpose in any reasonable amount of time.  I say, park this issue and move ahead.  Please review and give a 👍  / 👎 .

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by DusanJovic-NOAA** [comment]
How about creating ``develop`` branch?

**Comment by aerorahul** [comment]
> How about creating `develop` branch?

done.

**Comment by BenjaminTJohnson** [comment]
Public repositories on the JCSDA github are coming "soon".   Seems that I cannot push for this hard enough to make it happen, but it definitely has to happen around Oct 23:  JEDI public release, CRTM v2.4.0 public release.   I already have a REL_2.3.0_emc build release (not the development structure that we use internally).     

Of course, anyone who is interested can have access to the private repository to have a look, just send me your github username.

As soon as there's an update on the public availability, I will let you all know.

**Pull request merged**
